addons:
  sonarcloud:
    organization: "lherouin"
    token:
      secure: "d615jbtFMoyie+4Ghy7QVxJTaSopv8ohwQ5z8tYaLeTnMK18WflkLRK+rFo7VnW7DP85diQM+8VdhXeMmytOS04PZJB4zJHAhSWdjEQwOXbWpOX7rFqCD+Mel8/H7fDuw/qG6Qozd3JRjcIujoU6yMzaAPrKw+RaL7cH6Vl+taCp7GX7PcEyUGlNYM6TOotlykU6taEdUmwS9X4K3JLcT+ap31Mp7kBw0lvhxHRArEfQ0RQjjHOOMvgMcrLFloV4oV07A5PF/d6sYGsGUc1eJFHvFgr3MQkTUuMGZVl57osyVq0F2iOlrVOh5YbfNi/kFYX4rYDll2tVz747/TZwEKwz0f4tZi6aI1w0CH3TCwOm8bbqPN12o826vIa29L09q5UmhjpMsKZGe0z4LvI8mCSMOWXyP22qoU1lrcTMoQ+6es2QgsZ/kPu4qqORiO280kA4icVMNcKsSGTat1IF1mE6THaskGi/XmXHbhy32h4dGPVbr5MO+oXXfKD2oCka4ZfPGPJ085WB9aembPY+xhKijiq6V8AYhRhKOHsd51KJwdTsysSj2RzvMkhcX2n+dZuL+vLjIuaE//+pHJSjr17MGqrxry2WVW2m1ZA1Y1qBz/kVnFaYT+07Ls1MVm/CRbHTwS4y6ijydRHiFMeDsqbb52iP63SlYLgwtsWYMco="

script: mvn clean verify
